---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - context.kube-auth
  resources:
  - contexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - context.kube-auth
  resources:
  - contexts/finalizers
  verbs:
  - update
- apiGroups:
  - context.kube-auth
  resources:
  - contexts/status
  verbs:
  - get
  - patch
  - update
