name: continuous-integration.yml
on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run test
        run: make test

      - name: Run lint
        run: make lint

      - name: Run build
        run: make build

      - name: Run e2e test
        run: make e2e-test
