name: continuous-delivery.yml
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Test
        run: |
          echo "Testing the code"
          echo ${{ github.repository }}
          echo ${{ github.actor }}
          echo ${{ github.ref }}
          echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.project }}
          echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ matrix.project }}
          echo ${{ env.IMAGE_NAME }}
          echo ${{ matrix.project }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.project }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "./${{ matrix.project }}"
          file: ./Dockerfile
          build-args: |
            NPM_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
